### ISSUE TITLE
Latency Compensation and Caching

### ISSUE THREAD

**Issue by ccorcos** [kadirahq/lokka#1]
I like what you're doing here -- Relay has a ton of awesome features but they're so opinionated, its hard to work with on your own. But two really hard features are going to be latency compensation and caching -- I'm curious what your angle of attack is going to be on these?

After finding the babel-graphql-plugin, I didnt realize that graphql parses to a simple JSON tree:

https://github.com/ooflorent/babel-plugin-graphql

I suppose diffing wouldnt be too hard, but then theres a question of how to organize this graph... Its not going to be easy... :/

**Comment by arunoda** [comment]
You don't need babel-plugin for that. There are many ways to get the GraphQL AST. It's a tough to implement the cache locally. In this version, I just want to delegate it to some other layer Redux. Later on we can think of an well organized solution.
