### ISSUE TITLE
How can I mutate the array?

### ISSUE THREAD

**Issue by victorpavlenko** [kadirahq/lokka#12]
`userList: [
            ${data.user.map((a) =>`{`+ a.value +`}`)}
]`

Also in a.value contained object

In the end, I want to get something like this
`userList: [{
             name: "1111",
                 surname: "11111"
      },{
             name: "1111",
           surname: "11111"
        }]`

**Comment by MQuy** [comment]
@Xurma2, do you find a solution for this?

**Comment by victorpavlenko** [comment]
@MQuy no i dont understand how mutate if I have array

```
        imageList: [{  
           fileName: $fileName",
           url: $url,
           uuid: $uuid,
           deleteImage: $deleteImage,
           setMain: $setMain,
        }]
```
