### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by smolinari** [kadirahq/lokka#3]
Hi,

I am very interested in this project, as I don't like Relay simply because it is tied to React. 

I am contemplating using your gem of a package with vuex. https://github.com/vuejs/vuex

Though, I have two concerns. If I understand correctly, lokka doesn't yet manage any kind of store locally and you mention caching and validation. I would assume that means you do plan to add a client-side store(age) capability later? Could I feasibly use the vuex store to make the two work together?

Being lazy and not looking into the code, but does lokka support the introspection feature of GraphQL? (didn't see the docs mentioning it).

And, last question (which might show my lack of JS knowledge) will lokka (or does it now) support the ability to "collect" queries in a set of components, similar to how Relay does it with React components? 

Thanks for any support in advance!

Scott

**Comment by arunoda** [comment]
Hi,

You asked the question in the correct time. The main different with Relay and Lokka is, we don't have direct integration with the UI framework. It's all about the data store.

We already have a basic version of a cache and a Relay like declarative data fetching. I'll document it soon and do a blog post. Try our test-cases to have a look at it.

About the `introspection` feature: This is planned and will be available in the early next year. (Feb). With that, we could easily do validation in the client side and do more stuff in the caching layer.

**Comment by smolinari** [comment]
Thanks for the quick reply. 

The caching looks promising (hah, pun not intended). 

I am also still missing how lokka puts different queries together (which might be encapsulated with components) to end up with a single request (and one of the advantages of GraphQL). Can you shortly elaborate on that possibility?

Scott

**Comment by arunoda** [comment]
Checkout this app: https://github.com/kadira-samples/meteor-graphql-demo/tree/master/client

Both containers and components directories. It has some meteor specific stuffs. Pure JS version is coming soon. Actually it's already done.

**Comment by smolinari** [comment]
Thanks and I see how the fragments are being defined. But, that demo is using JSX. I'd really like to avoid JSX and React, if at all possible, and why I ended up with Vue. 

Anyhow, keep up the good work. I am now following this repo and looking forward to the finished caching and introspection parts. I'd love it, if lokka were to be something I could use like Vuex, with a simple API like Vuex has. So far, it looks like it is heading that way.

Scott

**Comment by arunoda** [comment]
Lokka stuffs are not related to React and JSX anyway. You could use if with vue for sure. I'll give it a try as well.

**Comment by smolinari** [comment]
@arunoda - hey. Any news about further developments? I noticed Meteor is also using GraphQL too now. This means more people will probably be looking at libraries like lokka for non-react/ relay solutions. I think that is good news.

Scott
