### ISSUE TITLE
Variables not supported for mutations

### ISSUE THREAD

**Issue by rafales** [kadirahq/lokka#9]
I can see that passing variables is not available for mutations (a workaround is to use `send()` function but it won't work with fragments).

Any plans on this? Can I somehow help?

**Comment by arunoda** [comment]
You can use `.query()`, which supports fragments.

**Comment by rafales** [comment]
Thanks for help. It may be a good idea to document this.

**Comment by arunoda** [comment]
Could you send me a PR?
